[package]
name = "rick_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
indicatif = "0.17.1"
dialoguer = "0.10.2"
redis = "0.22.1"
rocket = "0.5.0-rc.2"